services:
  tulip:
    build:
      context: ./
      network: host
    environment:
      - "TULIP__SERVER__HOST=${TULIP__SERVER__HOST:-0.0.0.0}"
      - "TULIP__SERVER__PORT=${TULIP__SERVER__PORT:-10530}"
      - "TULIP__COOKIES__DOMAIN=${TULIP__COOKIES__DOMAIN:-}"
      - "TULIP__SECRETS__AUTH=${TULIP__SECRETS__AUTH:-secret}"
      - "TULIP__URLS__PUBLIC=${TULIP__URLS__PUBLIC:-http://localhost:10530}"
      - "TULIP__BEAVER__SCHEME=${TULIP__BEAVER__SCHEME:-http}"
      - "TULIP__BEAVER__HOST=${TULIP__BEAVER__HOST:-localhost}"
      - "TULIP__BEAVER__PORT=${TULIP__BEAVER__PORT:-10500}"
      - "TULIP__BEAVER__PATH=${TULIP__BEAVER__PATH:-}"
      - "TULIP__SCORPION__PUBLIC__SCHEME=${TULIP__SCORPION__PUBLIC__SCHEME:-http}"
      - "TULIP__SCORPION__PUBLIC__HOST=${TULIP__SCORPION__PUBLIC__HOST:-localhost}"
      - "TULIP__SCORPION__PUBLIC__PORT=${TULIP__SCORPION__PUBLIC__PORT:-20000}"
      - "TULIP__SCORPION__PUBLIC__PATH=${TULIP__SCORPION__PUBLIC__PATH:-}"
      - "TULIP__SCORPION__PUBLIC__CLIENT=${TULIP__SCORPION__PUBLIC__CLIENT:-tulip}"
      - "TULIP__SCORPION__PUBLIC__SECRET=${TULIP__SCORPION__PUBLIC__SECRET:-secret}"
      - "TULIP__DEBUG=${TULIP__DEBUG:-true}"
    network_mode: host
