services:
  tulip:
    build:
      context: ./
      network: host
    environment:
      - "TULIP__APIS__BEAVER__HOST=${TULIP__APIS__BEAVER__HOST:-localhost}"
      - "TULIP__APIS__BEAVER__PATH=${TULIP__APIS__BEAVER__PATH:-}"
      - "TULIP__APIS__BEAVER__PORT=${TULIP__APIS__BEAVER__PORT:-10500}"
      - "TULIP__APIS__BEAVER__SCHEME=${TULIP__APIS__BEAVER__SCHEME:-http}"
      - "TULIP__APIS__ICANHAZDADJOKE__HOST=${TULIP__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "TULIP__APIS__ICANHAZDADJOKE__PATH=${TULIP__APIS__ICANHAZDADJOKE__PATH:-}"
      - "TULIP__APIS__ICANHAZDADJOKE__PORT=${TULIP__APIS__ICANHAZDADJOKE__PORT:-}"
      - "TULIP__APIS__ICANHAZDADJOKE__SCHEME=${TULIP__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "TULIP__DEBUG=${TULIP__DEBUG:-true}"
      - "TULIP__SERVER__HOST=${TULIP__SERVER__HOST:-0.0.0.0}"
      - "TULIP__SERVER__PORT=${TULIP__SERVER__PORT:-10530}"
    network_mode: host
