// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Success response payload for getting a random joke
 */
export type GetRandomJokeSuccessResponsePayload = {
  /**
   * Unique identifier of the joke
   */
  id: string;
  /**
   * The text of the joke
   */
  joke: string;
  /**
   * Status code of the response
   */
  status: 200;
};

export type GetRandomJokeRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetRandomJokeResponses = {
  /**
   * Successful response with a random joke
   */
  200: GetRandomJokeSuccessResponsePayload;
};

export type GetRandomJokeResponse =
  GetRandomJokeResponses[keyof GetRandomJokeResponses];
