// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * EventType
 *
 * Event types.
 */
export const SseModelsEventTypeSchema = z
  .enum([
    "test",
    "show-created",
    "show-updated",
    "show-deleted",
    "event-created",
    "event-updated",
    "event-deleted",
  ])
  .register(z.globalRegistry, {
    description: "Event types.",
  });

/**
 * _Event_type_OrderByInput
 */
export const ShowsModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const ShowsModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const ShowsModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const ShowsModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const ShowsModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: ShowsModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const ShowsModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const ShowsModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const ShowsModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const ShowsModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const ShowsModelsWeekdayRuleSchema = z
  .object({
    day: ShowsModelsWeekdaySchema,
    occurrence: ShowsModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

/**
 * EventType
 */
export const ShowsModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

/**
 * StringFilter
 */
export const ShowsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), ShowsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

export const ShowsModelsUpdateRequestIdSchema = z.uuid();

/**
 * ShowUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export const ShowsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    title: z.string().optional(),
    description: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for updating many records",
  });

export const ShowsModelsTimezoneSchema = z.string();

export const ShowsModelsMonthSchema = z.int().gte(1).lte(12);

export const ShowsModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const ShowsModelsHourSchema = z.int().gte(0).lte(23);

export const ShowsModelsMinuteSchema = z.int().gte(0).lte(59);

export const ShowsModelsSecondSchema = z.int().gte(0).lte(60);

/**
 * Frequency
 *
 * Frequency options.
 */
export const ShowsModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

export const ShowsModelsNaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export const ShowsModelsRecurrenceRuleSchema = z
  .object({
    frequency: ShowsModelsFrequencySchema,
    until: ShowsModelsNaiveDatetimeSchema.nullish().default(null),
    count: z.int().nullish().default(null),
    interval: z.int().nullish().default(null),
    bySeconds: z.array(ShowsModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(ShowsModelsMinuteSchema).nullish().default(null),
    byHours: z.array(ShowsModelsHourSchema).nullish().default(null),
    byWeekdays: z.array(ShowsModelsWeekdayRuleSchema).nullish().default(null),
    byMonthdays: z.array(ShowsModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(ShowsModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(ShowsModelsWeekSchema).nullish().default(null),
    byMonths: z.array(ShowsModelsMonthSchema).nullish().default(null),
    bySetPositions: z.array(z.int()).nullish().default(null),
    weekStart: ShowsModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

/**
 * Recurrence
 *
 * Recurrence data.
 */
export const ShowsModelsRecurrenceSchema = z
  .object({
    rule: ShowsModelsRecurrenceRuleSchema.nullish().default(null),
    include: z.array(ShowsModelsNaiveDatetimeSchema).nullish().default(null),
    exclude: z.array(ShowsModelsNaiveDatetimeSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence data.",
  });

/**
 * _Show_description_OrderByInput
 */
export const ShowDescriptionOrderByInputSchema = z.object({
  description: z.enum(["asc", "desc"]),
});

/**
 * _Show_title_OrderByInput
 */
export const ShowTitleOrderByInputSchema = z.object({
  title: z.enum(["asc", "desc"]),
});

/**
 * _Show_id_OrderByInput
 */
export const ShowIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

export const ShowOrderByInputSchema = z.union([
  ShowIdOrderByInputSchema,
  ShowTitleOrderByInputSchema,
  ShowDescriptionOrderByInputSchema,
]);

export const ShowsModelsListRequestOrderSchema = z
  .union([ShowOrderByInputSchema, z.array(ShowOrderByInputSchema)])
  .nullable();

export const ShowsModelsListRequestOffsetSchema = z.int().nullable();

export const ShowsModelsListRequestLimitSchema = z.int().nullable();

export const ShowsModelsGetRequestIdSchema = z.uuid();

export const ShowsModelsDeleteRequestIdSchema = z.uuid();

/**
 * ShowCreateWithoutRelationsInput
 *
 * Required arguments to the Show create method, without relations
 */
export const ShowsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    description: z.string().nullish(),
    title: z.string(),
  })
  .register(z.globalRegistry, {
    description:
      "Required arguments to the Show create method, without relations",
  });

/**
 * _Event_type_OrderByInput
 */
export const ScheduleModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const ScheduleModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const ScheduleModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const ScheduleModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const ScheduleModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: ScheduleModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const ScheduleModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const ScheduleModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const ScheduleModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const ScheduleModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const ScheduleModelsWeekdayRuleSchema = z
  .object({
    day: ScheduleModelsWeekdaySchema,
    occurrence: ScheduleModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

export const ScheduleModelsTimezoneSchema = z.string();

/**
 * StringFilter
 */
export const ScheduleModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), ScheduleModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

/**
 * EventType
 */
export const ScheduleModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

export const ScheduleModelsMonthSchema = z.int().gte(1).lte(12);

export const ScheduleModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const ScheduleModelsHourSchema = z.int().gte(0).lte(23);

export const ScheduleModelsMinuteSchema = z.int().gte(0).lte(59);

export const ScheduleModelsSecondSchema = z.int().gte(0).lte(60);

/**
 * Frequency
 *
 * Frequency options.
 */
export const ScheduleModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

export const ScheduleModelsNaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export const ScheduleModelsRecurrenceRuleSchema = z
  .object({
    frequency: ScheduleModelsFrequencySchema,
    until: ScheduleModelsNaiveDatetimeSchema.nullish().default(null),
    count: z.int().nullish().default(null),
    interval: z.int().nullish().default(null),
    bySeconds: z.array(ScheduleModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(ScheduleModelsMinuteSchema).nullish().default(null),
    byHours: z.array(ScheduleModelsHourSchema).nullish().default(null),
    byWeekdays: z
      .array(ScheduleModelsWeekdayRuleSchema)
      .nullish()
      .default(null),
    byMonthdays: z.array(ScheduleModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(ScheduleModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(ScheduleModelsWeekSchema).nullish().default(null),
    byMonths: z.array(ScheduleModelsMonthSchema).nullish().default(null),
    bySetPositions: z.array(z.int()).nullish().default(null),
    weekStart: ScheduleModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

/**
 * Recurrence
 *
 * Recurrence data.
 */
export const ScheduleModelsRecurrenceSchema = z
  .object({
    rule: ScheduleModelsRecurrenceRuleSchema.nullish().default(null),
    include: z.array(ScheduleModelsNaiveDatetimeSchema).nullish().default(null),
    exclude: z.array(ScheduleModelsNaiveDatetimeSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence data.",
  });

/**
 * EventInstance
 *
 * Event instance data.
 */
export const EventInstanceSchema = z
  .object({
    start: ScheduleModelsNaiveDatetimeSchema,
    end: ScheduleModelsNaiveDatetimeSchema,
  })
  .register(z.globalRegistry, {
    description: "Event instance data.",
  });

export const ScheduleModelsEventOrderByInputSchema = z.union([
  ScheduleModelsEventIdOrderByInputSchema,
  ScheduleModelsEventTypeOrderByInputSchema,
  ScheduleModelsEventShowIdOrderByInputSchema,
]);

export const ScheduleModelsListRequestOrderSchema = z
  .union([
    ScheduleModelsEventOrderByInputSchema,
    z.array(ScheduleModelsEventOrderByInputSchema),
  ])
  .nullable();

export const ScheduleModelsListRequestOffsetSchema = z.int().nullable();

export const ScheduleModelsListRequestLimitSchema = z.int().nullable();

/**
 * _Event_type_OrderByInput
 */
export const EventsModelsEventTypeOrderByInputSchema = z.object({
  type: z.enum(["asc", "desc"]),
});

/**
 * _Event_showId_OrderByInput
 */
export const EventsModelsEventShowIdOrderByInputSchema = z.object({
  showId: z.enum(["asc", "desc"]),
});

/**
 * _Event_id_OrderByInput
 */
export const EventsModelsEventIdOrderByInputSchema = z.object({
  id: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceInner
 */
export const EventsModelsEventRelevanceInnerSchema = z.object({
  fields: z.array(z.enum(["id", "type", "showId"])),
  search: z.string(),
  sort: z.enum(["asc", "desc"]),
});

/**
 * _Event_RelevanceOrderByInput
 */
export const EventsModelsEventRelevanceOrderByInputSchema = z.object({
  _relevance: EventsModelsEventRelevanceInnerSchema,
});

/**
 * _EventWhereUnique_id_Input
 */
export const EventsModelsEventWhereUniqueIdInputSchema = z.object({
  id: z.string(),
});

export const EventsModelsYeardaySchema = z.union([
  z.int().gte(-366).lte(-1),
  z.int().gte(1).lte(366),
]);

export const EventsModelsWeekSchema = z.union([
  z.int().gte(-53).lte(-1),
  z.int().gte(1).lte(53),
]);

/**
 * Weekday
 *
 * Weekday options.
 */
export const EventsModelsWeekdaySchema = z
  .enum([
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
  ])
  .register(z.globalRegistry, {
    description: "Weekday options.",
  });

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export const EventsModelsWeekdayRuleSchema = z
  .object({
    day: EventsModelsWeekdaySchema,
    occurrence: EventsModelsWeekSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Day rule data.",
  });

/**
 * StringFilter
 */
export const EventsModelsStringFilterSchema = z.object({
  equals: z.string().optional(),
  notIn: z.array(z.string()).optional(),
  lt: z.string().optional(),
  lte: z.string().optional(),
  gt: z.string().optional(),
  gte: z.string().optional(),
  contains: z.string().optional(),
  startswith: z.string().optional(),
  endswith: z.string().optional(),
  in: z.array(z.string()).optional(),
  get not() {
    return z.union([z.string(), EventsModelsStringFilterSchema]).optional();
  },
  mode: z.enum(["default", "insensitive"]).optional(),
  search: z.string().optional(),
});

/**
 * EventType
 */
export const EventsModelsEventTypeSchema = z.enum([
  "live",
  "replay",
  "prerecorded",
]);

export const EventsModelsUpdateRequestIdSchema = z.uuid();

export const EventsModelsMonthSchema = z.int().gte(1).lte(12);

export const EventsModelsMonthdaySchema = z.union([
  z.int().gte(-31).lte(-1),
  z.int().gte(1).lte(31),
]);

export const EventsModelsHourSchema = z.int().gte(0).lte(23);

export const EventsModelsMinuteSchema = z.int().gte(0).lte(59);

export const EventsModelsSecondSchema = z.int().gte(0).lte(60);

/**
 * Frequency
 *
 * Frequency options.
 */
export const EventsModelsFrequencySchema = z
  .enum([
    "secondly",
    "minutely",
    "hourly",
    "daily",
    "weekly",
    "monthly",
    "yearly",
  ])
  .register(z.globalRegistry, {
    description: "Frequency options.",
  });

export const EventsModelsNaiveDatetimeSchema = z.iso.datetime({
  offset: true,
  local: true,
});

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export const EventsModelsRecurrenceRuleSchema = z
  .object({
    frequency: EventsModelsFrequencySchema,
    until: EventsModelsNaiveDatetimeSchema.nullish().default(null),
    count: z.int().nullish().default(null),
    interval: z.int().nullish().default(null),
    bySeconds: z.array(EventsModelsSecondSchema).nullish().default(null),
    byMinutes: z.array(EventsModelsMinuteSchema).nullish().default(null),
    byHours: z.array(EventsModelsHourSchema).nullish().default(null),
    byWeekdays: z.array(EventsModelsWeekdayRuleSchema).nullish().default(null),
    byMonthdays: z.array(EventsModelsMonthdaySchema).nullish().default(null),
    byYeardays: z.array(EventsModelsYeardaySchema).nullish().default(null),
    byWeeks: z.array(EventsModelsWeekSchema).nullish().default(null),
    byMonths: z.array(EventsModelsMonthSchema).nullish().default(null),
    bySetPositions: z.array(z.int()).nullish().default(null),
    weekStart: EventsModelsWeekdaySchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence rule data.",
  });

/**
 * Recurrence
 *
 * Recurrence data.
 */
export const EventsModelsRecurrenceSchema = z
  .object({
    rule: EventsModelsRecurrenceRuleSchema.nullish().default(null),
    include: z.array(EventsModelsNaiveDatetimeSchema).nullish().default(null),
    exclude: z.array(EventsModelsNaiveDatetimeSchema).nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Recurrence data.",
  });

export const EventsModelsTimezoneSchema = z.string();

/**
 * EventUpdateInput
 *
 * Input data to update an event.
 */
export const EventsModelsUpdateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    type: EventsModelsEventTypeSchema.optional(),
    start: EventsModelsNaiveDatetimeSchema.optional(),
    end: EventsModelsNaiveDatetimeSchema.optional(),
    timezone: EventsModelsTimezoneSchema.optional(),
    recurrence: EventsModelsRecurrenceSchema.nullish(),
  })
  .register(z.globalRegistry, {
    description: "Input data to update an event.",
  });

export const EventsModelsEventOrderByInputSchema = z.union([
  EventsModelsEventIdOrderByInputSchema,
  EventsModelsEventTypeOrderByInputSchema,
  EventsModelsEventShowIdOrderByInputSchema,
]);

export const EventsModelsListRequestOrderSchema = z
  .union([
    EventsModelsEventOrderByInputSchema,
    z.array(EventsModelsEventOrderByInputSchema),
  ])
  .nullable();

export const EventsModelsListRequestOffsetSchema = z.int().nullable();

export const EventsModelsListRequestLimitSchema = z.int().nullable();

export const EventsModelsGetRequestIdSchema = z.uuid();

export const EventsModelsDeleteRequestIdSchema = z.uuid();

/**
 * EventCreateInput
 *
 * Input data to create an event.
 */
export const EventsModelsCreateRequestDataSchema = z
  .object({
    id: z.string().optional(),
    showId: z.string().optional(),
    type: EventsModelsEventTypeSchema,
    start: EventsModelsNaiveDatetimeSchema,
    end: EventsModelsNaiveDatetimeSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullish(),
  })
  .register(z.globalRegistry, {
    description: "Input data to create an event.",
  });

/**
 * TimeRangeQuery
 *
 * Query for events in a time range.
 */
export const TimeRangeQuerySchema = z
  .object({
    type: z
      .literal("time-range")
      .register(z.globalRegistry, {
        description: "Type of the query.",
      })
      .optional()
      .default("time-range"),
    start: EventsModelsNaiveDatetimeSchema.nullish().default(null),
    end: EventsModelsNaiveDatetimeSchema.nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Query for events in a time range.",
  });

/**
 * Result
 *
 * Result of the test.
 */
export const TestResponseResultSchema = z
  .object({
    success: z.boolean().register(z.globalRegistry, {
      description: "Indicates if the test was successful.",
    }),
    message: z.string().register(z.globalRegistry, {
      description: "Message returned from the test.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Result of the test.",
  });

/**
 * Parameters
 *
 * Parameters for testing.
 */
export const ParametersSchema = z
  .object({
    message: z.string().nullish().default(null),
  })
  .register(z.globalRegistry, {
    description: "Parameters for testing.",
  });

export const TestRequestParametersSchema = ParametersSchema.nullable();

export const SubscribeRequestTypesSchema = z
  .union([z.string(), z.array(SseModelsEventTypeSchema)])
  .nullable();

/**
 * RecurringQuery
 *
 * Query for recurring events.
 */
export const RecurringQuerySchema = z
  .object({
    type: z
      .literal("recurring")
      .register(z.globalRegistry, {
        description: "Type of the query.",
      })
      .optional()
      .default("recurring"),
    recurring: z.boolean().register(z.globalRegistry, {
      description: "Whether to search for recurring or non-recurring events.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Query for recurring events.",
  });

export const QuerySchema = z.union([
  z
    .object({
      type: z.literal("TimeRangeQuery"),
    })
    .and(TimeRangeQuerySchema),
  z
    .object({
      type: z.literal("RecurringQuery"),
    })
    .and(RecurringQuerySchema),
]);

export const ListRequestStartSchema =
  ScheduleModelsNaiveDatetimeSchema.nullable();

export const ListRequestQuerySchema = QuerySchema.nullable();

export const ListRequestEndSchema =
  ScheduleModelsNaiveDatetimeSchema.nullable();

export const ShowsModelsUpdateRequestIncludeSchema = z
  .lazy(() => ShowIncludeSchema)
  .nullable();

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const ShowsModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([
        z.boolean(),
        z.lazy((): any => ShowsModelsFindManyEventArgsFromShowSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const ShowsModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        ShowsModelsEventIdOrderByInputSchema,
        ShowsModelsEventTypeOrderByInputSchema,
        ShowsModelsEventShowIdOrderByInputSchema,
        ShowsModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            ShowsModelsEventIdOrderByInputSchema,
            ShowsModelsEventTypeOrderByInputSchema,
            ShowsModelsEventShowIdOrderByInputSchema,
            ShowsModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: z.lazy((): any => ShowsModelsEventWhereInputSchema).optional(),
    cursor: ShowsModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: z
      .lazy((): any => ShowsModelsEventIncludeFromEventSchema)
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const ShowsModelsShowArgsFromEventSchema = z
  .object({
    include: ShowsModelsShowIncludeFromShowSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const ShowsModelsEventIncludeFromEventSchema = z
  .object({
    show: z.union([z.boolean(), ShowsModelsShowArgsFromEventSchema]).optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const ShowsModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    description: z.union([z.string(), ShowsModelsStringFilterSchema]).nullish(),
    events: z
      .lazy((): any => ShowsModelsEventListRelationFilterSchema)
      .optional(),
    and: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
    or: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
    not: z.array(z.lazy((): any => ShowsModelsShowWhereInputSchema)).optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * ShowRelationFilter
 */
export const ShowsModelsShowRelationFilterSchema = z.object({
  is: ShowsModelsShowWhereInputSchema.optional(),
  isNot: ShowsModelsShowWhereInputSchema.optional(),
});

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const ShowsModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    type: ShowsModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), ShowsModelsStringFilterSchema]).optional(),
    show: ShowsModelsShowRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => ShowsModelsEventWhereInputSchema))
      .optional(),
    or: z.array(z.lazy((): any => ShowsModelsEventWhereInputSchema)).optional(),
    not: z
      .array(z.lazy((): any => ShowsModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * EventListRelationFilter
 */
export const ShowsModelsEventListRelationFilterSchema = z.object({
  some: ShowsModelsEventWhereInputSchema.optional(),
  none: ShowsModelsEventWhereInputSchema.optional(),
  every: ShowsModelsEventWhereInputSchema.optional(),
});

/**
 * ShowInclude
 *
 * Show relational arguments
 */
export const ShowIncludeSchema = z
  .object({
    events: z
      .union([z.boolean(), ShowsModelsFindManyEventArgsFromShowSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show relational arguments",
  });

/**
 * Show
 *
 * Show data.
 */
export const ShowsModelsShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => ShowsModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const ShowsModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: ShowsModelsEventTypeSchema,
    showId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show that the event belongs to.",
    }),
    show: ShowsModelsShowSchema.nullable(),
    start: ShowsModelsNaiveDatetimeSchema,
    end: ShowsModelsNaiveDatetimeSchema,
    timezone: ShowsModelsTimezoneSchema,
    recurrence: ShowsModelsRecurrenceSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * ShowList
 *
 * List of shows.
 */
export const ShowsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of shows that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    shows: z.array(ShowsModelsShowSchema).register(z.globalRegistry, {
      description: "Shows that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of shows.",
  });

export const ShowsModelsListRequestWhereSchema =
  ShowsModelsShowWhereInputSchema.nullable();

export const ShowsModelsListRequestIncludeSchema = ShowIncludeSchema.nullable();

export const ShowsModelsGetRequestIncludeSchema = ShowIncludeSchema.nullable();

export const ShowsModelsCreateRequestIncludeSchema =
  ShowIncludeSchema.nullable();

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const ScheduleModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), ScheduleModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), ScheduleModelsStringFilterSchema]).optional(),
    description: z
      .union([z.string(), ScheduleModelsStringFilterSchema])
      .nullish(),
    events: z
      .lazy((): any => ScheduleModelsEventListRelationFilterSchema)
      .optional(),
    and: z
      .array(z.lazy((): any => ScheduleModelsShowWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => ScheduleModelsShowWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => ScheduleModelsShowWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const ScheduleModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), ScheduleModelsStringFilterSchema]).optional(),
    type: ScheduleModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), ScheduleModelsStringFilterSchema]).optional(),
    show: z.lazy((): any => ScheduleModelsShowRelationFilterSchema).optional(),
    and: z
      .array(z.lazy((): any => ScheduleModelsEventWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => ScheduleModelsEventWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => ScheduleModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * EventListRelationFilter
 */
export const ScheduleModelsEventListRelationFilterSchema = z.object({
  some: ScheduleModelsEventWhereInputSchema.optional(),
  none: ScheduleModelsEventWhereInputSchema.optional(),
  every: ScheduleModelsEventWhereInputSchema.optional(),
});

/**
 * ShowRelationFilter
 */
export const ScheduleModelsShowRelationFilterSchema = z.object({
  is: ScheduleModelsShowWhereInputSchema.optional(),
  isNot: ScheduleModelsShowWhereInputSchema.optional(),
});

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const ScheduleModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([
        z.boolean(),
        z.lazy((): any => ScheduleModelsFindManyEventArgsFromShowSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const ScheduleModelsShowArgsFromEventSchema = z
  .object({
    include: ScheduleModelsShowIncludeFromShowSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const ScheduleModelsEventIncludeFromEventSchema = z
  .object({
    show: z
      .union([z.boolean(), ScheduleModelsShowArgsFromEventSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const ScheduleModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        ScheduleModelsEventIdOrderByInputSchema,
        ScheduleModelsEventTypeOrderByInputSchema,
        ScheduleModelsEventShowIdOrderByInputSchema,
        ScheduleModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            ScheduleModelsEventIdOrderByInputSchema,
            ScheduleModelsEventTypeOrderByInputSchema,
            ScheduleModelsEventShowIdOrderByInputSchema,
            ScheduleModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: ScheduleModelsEventWhereInputSchema.optional(),
    cursor: ScheduleModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: ScheduleModelsEventIncludeFromEventSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * Show
 *
 * Show data.
 */
export const ScheduleModelsShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => ScheduleModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const ScheduleModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: ScheduleModelsEventTypeSchema,
    showId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show that the event belongs to.",
    }),
    show: ScheduleModelsShowSchema.nullable(),
    start: ScheduleModelsNaiveDatetimeSchema,
    end: ScheduleModelsNaiveDatetimeSchema,
    timezone: ScheduleModelsTimezoneSchema,
    recurrence: ScheduleModelsRecurrenceSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * ScheduleList
 *
 * List of event schedules.
 */
export const ScheduleModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of schedules that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    schedules: z
      .array(z.lazy(() => ScheduleSchema))
      .register(z.globalRegistry, {
        description: "Schedules that matched the request.",
      }),
  })
  .register(z.globalRegistry, {
    description: "List of event schedules.",
  });

/**
 * Schedule
 *
 * Schedule data.
 */
export const ScheduleSchema = z
  .object({
    event: ScheduleModelsEventSchema,
    instances: z.array(EventInstanceSchema).register(z.globalRegistry, {
      description: "Event instances.",
    }),
  })
  .register(z.globalRegistry, {
    description: "Schedule data.",
  });

export const ScheduleModelsListRequestWhereSchema =
  ScheduleModelsEventWhereInputSchema.nullable();

export const ScheduleModelsListRequestIncludeSchema = z
  .lazy(() => ScheduleModelsEventIncludeSchema)
  .nullable();

/**
 * EventInclude
 *
 * Event relational arguments
 */
export const ScheduleModelsEventIncludeSchema = z
  .object({
    show: z
      .union([z.boolean(), ScheduleModelsShowArgsFromEventSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event relational arguments",
  });

export const EventsModelsUpdateRequestIncludeSchema = z
  .lazy(() => EventsModelsEventIncludeSchema)
  .nullable();

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export const EventsModelsEventIncludeFromEventSchema = z
  .object({
    show: z
      .union([
        z.boolean(),
        z.lazy((): any => EventsModelsShowArgsFromEventSchema),
      ])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Event",
  });

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export const EventsModelsShowArgsFromEventSchema = z
  .object({
    include: z
      .lazy((): any => EventsModelsShowIncludeFromShowSchema)
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Event",
  });

/**
 * EventListRelationFilter
 */
export const EventsModelsEventListRelationFilterSchema = z.object({
  get some() {
    return EventsModelsEventWhereInputSchema.optional();
  },
  get none() {
    return EventsModelsEventWhereInputSchema.optional();
  },
  get every() {
    return EventsModelsEventWhereInputSchema.optional();
  },
});

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export const EventsModelsEventWhereInputSchema = z
  .object({
    id: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    type: EventsModelsEventTypeSchema.optional(),
    showId: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    show: z.lazy((): any => EventsModelsShowRelationFilterSchema).optional(),
    and: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
    or: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
    not: z
      .array(z.lazy((): any => EventsModelsEventWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event arguments for searching",
  });

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export const EventsModelsShowWhereInputSchema = z
  .object({
    id: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    title: z.union([z.string(), EventsModelsStringFilterSchema]).optional(),
    description: z
      .union([z.string(), EventsModelsStringFilterSchema])
      .nullish(),
    events: EventsModelsEventListRelationFilterSchema.optional(),
    and: z
      .array(z.lazy((): any => EventsModelsShowWhereInputSchema))
      .optional(),
    or: z.array(z.lazy((): any => EventsModelsShowWhereInputSchema)).optional(),
    not: z
      .array(z.lazy((): any => EventsModelsShowWhereInputSchema))
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Show arguments for searching",
  });

/**
 * ShowRelationFilter
 */
export const EventsModelsShowRelationFilterSchema = z.object({
  is: EventsModelsShowWhereInputSchema.optional(),
  isNot: EventsModelsShowWhereInputSchema.optional(),
});

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export const EventsModelsFindManyEventArgsFromShowSchema = z
  .object({
    take: z.int().optional(),
    skip: z.int().optional(),
    orderBy: z
      .union([
        EventsModelsEventIdOrderByInputSchema,
        EventsModelsEventTypeOrderByInputSchema,
        EventsModelsEventShowIdOrderByInputSchema,
        EventsModelsEventRelevanceOrderByInputSchema,
        z.array(
          z.union([
            EventsModelsEventIdOrderByInputSchema,
            EventsModelsEventTypeOrderByInputSchema,
            EventsModelsEventShowIdOrderByInputSchema,
            EventsModelsEventRelevanceOrderByInputSchema,
          ]),
        ),
      ])
      .optional(),
    where: EventsModelsEventWhereInputSchema.optional(),
    cursor: EventsModelsEventWhereUniqueIdInputSchema.optional(),
    distinct: z.array(z.enum(["id", "type", "showId"])).optional(),
    include: EventsModelsEventIncludeFromEventSchema.optional(),
  })
  .register(z.globalRegistry, {
    description: "Arguments for Show",
  });

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export const EventsModelsShowIncludeFromShowSchema = z
  .object({
    events: z
      .union([z.boolean(), EventsModelsFindManyEventArgsFromShowSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Relational arguments for Show",
  });

/**
 * EventInclude
 *
 * Event relational arguments
 */
export const EventsModelsEventIncludeSchema = z
  .object({
    show: z
      .union([z.boolean(), EventsModelsShowArgsFromEventSchema])
      .optional(),
  })
  .register(z.globalRegistry, {
    description: "Event relational arguments",
  });

/**
 * Show
 *
 * Show data.
 */
export const EventsModelsShowSchema = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(z.lazy((): any => EventsModelsEventSchema)).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const EventsModelsEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: EventsModelsEventTypeSchema,
    showId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show that the event belongs to.",
    }),
    show: EventsModelsShowSchema.nullable(),
    start: EventsModelsNaiveDatetimeSchema,
    end: EventsModelsNaiveDatetimeSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

/**
 * EventList
 *
 * List of events.
 */
export const EventsModelsListResponseResultsSchema = z
  .object({
    count: z.int().register(z.globalRegistry, {
      description: "Total number of events that matched the query.",
    }),
    limit: z.int().nullable(),
    offset: z.int().nullable(),
    events: z.array(EventsModelsEventSchema).register(z.globalRegistry, {
      description: "Events that matched the request.",
    }),
  })
  .register(z.globalRegistry, {
    description: "List of events.",
  });

export const EventsModelsListRequestWhereSchema =
  EventsModelsEventWhereInputSchema.nullable();

export const EventsModelsListRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

export const EventsModelsGetRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

export const EventsModelsCreateRequestIncludeSchema =
  EventsModelsEventIncludeSchema.nullable();

/**
 * Show
 *
 * Show data.
 */
export const GetResponseShowSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show.",
    }),
    title: z.string().register(z.globalRegistry, {
      description: "Title of the show.",
    }),
    description: z.string().nullable(),
    events: z.array(ShowsModelsEventSchema).nullable(),
  })
  .register(z.globalRegistry, {
    description: "Show data.",
  });

/**
 * Event
 *
 * Event data.
 */
export const GetResponseEventSchema = z
  .object({
    id: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the event.",
    }),
    type: EventsModelsEventTypeSchema,
    showId: z.uuid().register(z.globalRegistry, {
      description: "Identifier of the show that the event belongs to.",
    }),
    show: EventsModelsShowSchema.nullable(),
    start: EventsModelsNaiveDatetimeSchema,
    end: EventsModelsNaiveDatetimeSchema,
    timezone: EventsModelsTimezoneSchema,
    recurrence: EventsModelsRecurrenceSchema.nullable(),
  })
  .register(z.globalRegistry, {
    description: "Event data.",
  });

export const EventsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: EventsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const EventsIdDeleteResponseSchema = z
  .void()
  .register(z.globalRegistry, {
    description: "Request fulfilled, nothing follows",
  });

export const PingPingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingPingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const PingHeadpingRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const PingHeadpingResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const ShowsIdDeleteRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: ShowsModelsDeleteRequestIdSchema,
  }),
  query: z.never().optional(),
});

/**
 * Request fulfilled, nothing follows
 */
export const ShowsIdDeleteResponseSchema = z.void().register(z.globalRegistry, {
  description: "Request fulfilled, nothing follows",
});

export const SseSubscribeRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      types: z.union([SubscribeRequestTypesSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, stream of Server-Sent Events follows
 */
export const SseSubscribeResponseSchema = z
  .string()
  .register(z.globalRegistry, {
    description: "Request fulfilled, stream of Server-Sent Events follows",
  });

export const TestTestRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      parameters: z.union([TestRequestParametersSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const TestTestResponseSchema = TestResponseResultSchema;

export const EventsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z
        .union([EventsModelsListRequestLimitSchema, z.string()])
        .nullish(),
      offset: z
        .union([EventsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z
        .union([EventsModelsListRequestWhereSchema, z.string()])
        .nullish(),
      query: z.union([ListRequestQuerySchema, z.string()]).nullish(),
      include: z
        .union([EventsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([EventsModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsListResponseSchema = EventsModelsListResponseResultsSchema;

export const EventsCreateRequestSchema = z.object({
  body: EventsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([EventsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const EventsCreateResponseSchema = EventsModelsEventSchema;

export const EventsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: EventsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([EventsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsIdGetResponseSchema = GetResponseEventSchema;

export const EventsIdUpdateRequestSchema = z.object({
  body: EventsModelsUpdateRequestDataSchema,
  path: z.object({
    id: EventsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([EventsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const EventsIdUpdateResponseSchema = EventsModelsEventSchema;

export const ScheduleListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      start: z.union([ListRequestStartSchema, z.string()]).nullish(),
      end: z.union([ListRequestEndSchema, z.string()]).nullish(),
      limit: z
        .union([ScheduleModelsListRequestLimitSchema, z.string()])
        .nullish(),
      offset: z
        .union([ScheduleModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z
        .union([ScheduleModelsListRequestWhereSchema, z.string()])
        .nullish(),
      include: z
        .union([ScheduleModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z
        .union([ScheduleModelsListRequestOrderSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ScheduleListResponseSchema =
  ScheduleModelsListResponseResultsSchema;

export const ShowsListRequestSchema = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      limit: z.union([ShowsModelsListRequestLimitSchema, z.string()]).nullish(),
      offset: z
        .union([ShowsModelsListRequestOffsetSchema, z.string()])
        .nullish(),
      where: z.union([ShowsModelsListRequestWhereSchema, z.string()]).nullish(),
      include: z
        .union([ShowsModelsListRequestIncludeSchema, z.string()])
        .nullish(),
      order: z.union([ShowsModelsListRequestOrderSchema, z.string()]).nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsListResponseSchema = ShowsModelsListResponseResultsSchema;

export const ShowsCreateRequestSchema = z.object({
  body: ShowsModelsCreateRequestDataSchema,
  path: z.never().optional(),
  query: z
    .object({
      include: z
        .union([ShowsModelsCreateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Document created, URL follows
 */
export const ShowsCreateResponseSchema = ShowsModelsShowSchema;

export const ShowsIdGetRequestSchema = z.object({
  body: z.never().optional(),
  path: z.object({
    id: ShowsModelsGetRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([ShowsModelsGetRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsIdGetResponseSchema = GetResponseShowSchema;

export const ShowsIdUpdateRequestSchema = z.object({
  body: ShowsModelsUpdateRequestDataSchema,
  path: z.object({
    id: ShowsModelsUpdateRequestIdSchema,
  }),
  query: z
    .object({
      include: z
        .union([ShowsModelsUpdateRequestIncludeSchema, z.string()])
        .nullish(),
    })
    .optional(),
});

/**
 * Request fulfilled, document follows
 */
export const ShowsIdUpdateResponseSchema = ShowsModelsShowSchema;
