// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import {
  EventsCreateRequestSchema,
  EventsCreateResponseSchema,
  EventsIdDeleteRequestSchema,
  EventsIdDeleteResponseSchema,
  EventsIdGetRequestSchema,
  EventsIdGetResponseSchema,
  EventsIdUpdateRequestSchema,
  EventsIdUpdateResponseSchema,
  EventsListRequestSchema,
  EventsListResponseSchema,
  PingHeadpingRequestSchema,
  PingHeadpingResponseSchema,
  PingPingRequestSchema,
  PingPingResponseSchema,
  ScheduleListRequestSchema,
  ScheduleListResponseSchema,
  ShowsCreateRequestSchema,
  ShowsCreateResponseSchema,
  ShowsIdDeleteRequestSchema,
  ShowsIdDeleteResponseSchema,
  ShowsIdGetRequestSchema,
  ShowsIdGetResponseSchema,
  ShowsIdUpdateRequestSchema,
  ShowsIdUpdateResponseSchema,
  ShowsListRequestSchema,
  ShowsListResponseSchema,
  SseSubscribeRequestSchema,
  SseSubscribeResponseSchema,
  TestTestRequestSchema,
  TestTestResponseSchema,
} from "./schemas";
import type {
  EventsCreateErrors,
  EventsCreateRequest,
  EventsCreateResponses,
  EventsIdDeleteErrors,
  EventsIdDeleteRequest,
  EventsIdDeleteResponses,
  EventsIdGetErrors,
  EventsIdGetRequest,
  EventsIdGetResponses,
  EventsIdUpdateErrors,
  EventsIdUpdateRequest,
  EventsIdUpdateResponses,
  EventsListErrors,
  EventsListRequest,
  EventsListResponses,
  PingHeadpingRequest,
  PingHeadpingResponses,
  PingPingRequest,
  PingPingResponses,
  ScheduleListErrors,
  ScheduleListRequest,
  ScheduleListResponses,
  ShowsCreateErrors,
  ShowsCreateRequest,
  ShowsCreateResponses,
  ShowsIdDeleteErrors,
  ShowsIdDeleteRequest,
  ShowsIdDeleteResponses,
  ShowsIdGetErrors,
  ShowsIdGetRequest,
  ShowsIdGetResponses,
  ShowsIdUpdateErrors,
  ShowsIdUpdateRequest,
  ShowsIdUpdateResponses,
  ShowsListErrors,
  ShowsListRequest,
  ShowsListResponses,
  SseSubscribeErrors,
  SseSubscribeRequest,
  SseSubscribeResponses,
  TestTestErrors,
  TestTestRequest,
  TestTestResponses,
} from "./types";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args: { client: Client }) {
    this.client = args.client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args: { client: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args.key);
  }

  /**
   * List events
   *
   * List events that match the request.
   */
  public eventsList<ThrowOnError extends boolean = false>(
    options?: Options<EventsListRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      EventsListResponses,
      EventsListErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await EventsListRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await EventsListResponseSchema.parseAsync(data),
      url: "/events",
      ...options,
    });
  }

  /**
   * Create event
   *
   * Create a new event.
   */
  public eventsCreate<ThrowOnError extends boolean = false>(
    options: Options<EventsCreateRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      EventsCreateResponses,
      EventsCreateErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await EventsCreateRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await EventsCreateResponseSchema.parseAsync(data),
      url: "/events",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete event
   *
   * Delete an event by ID.
   */
  public eventsIdDelete<ThrowOnError extends boolean = false>(
    options: Options<EventsIdDeleteRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      EventsIdDeleteResponses,
      EventsIdDeleteErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await EventsIdDeleteRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await EventsIdDeleteResponseSchema.parseAsync(data),
      url: "/events/{id}",
      ...options,
    });
  }

  /**
   * Get event
   *
   * Get an event by ID.
   */
  public eventsIdGet<ThrowOnError extends boolean = false>(
    options: Options<EventsIdGetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      EventsIdGetResponses,
      EventsIdGetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await EventsIdGetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await EventsIdGetResponseSchema.parseAsync(data),
      url: "/events/{id}",
      ...options,
    });
  }

  /**
   * Update event
   *
   * Update an event by ID.
   */
  public eventsIdUpdate<ThrowOnError extends boolean = false>(
    options: Options<EventsIdUpdateRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).patch<
      EventsIdUpdateResponses,
      EventsIdUpdateErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await EventsIdUpdateRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await EventsIdUpdateResponseSchema.parseAsync(data),
      url: "/events/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Ping
   *
   * Ping.
   */
  public pingPing<ThrowOnError extends boolean = false>(
    options?: Options<PingPingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      PingPingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingPingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingPingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Ping headers
   *
   * Ping headers.
   */
  public pingHeadping<ThrowOnError extends boolean = false>(
    options?: Options<PingHeadpingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).head<
      PingHeadpingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingHeadpingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingHeadpingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * List schedules
   *
   * List event schedules with instances between two dates.
   */
  public scheduleList<ThrowOnError extends boolean = false>(
    options?: Options<ScheduleListRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      ScheduleListResponses,
      ScheduleListErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ScheduleListRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ScheduleListResponseSchema.parseAsync(data),
      url: "/schedule",
      ...options,
    });
  }

  /**
   * List shows
   *
   * List shows that match the request.
   */
  public showsList<ThrowOnError extends boolean = false>(
    options?: Options<ShowsListRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      ShowsListResponses,
      ShowsListErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ShowsListRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ShowsListResponseSchema.parseAsync(data),
      url: "/shows",
      ...options,
    });
  }

  /**
   * Create show
   *
   * Create a new show.
   */
  public showsCreate<ThrowOnError extends boolean = false>(
    options: Options<ShowsCreateRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      ShowsCreateResponses,
      ShowsCreateErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ShowsCreateRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ShowsCreateResponseSchema.parseAsync(data),
      url: "/shows",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete show
   *
   * Delete a show by ID.
   */
  public showsIdDelete<ThrowOnError extends boolean = false>(
    options: Options<ShowsIdDeleteRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      ShowsIdDeleteResponses,
      ShowsIdDeleteErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ShowsIdDeleteRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ShowsIdDeleteResponseSchema.parseAsync(data),
      url: "/shows/{id}",
      ...options,
    });
  }

  /**
   * Get show
   *
   * Get a show by ID.
   */
  public showsIdGet<ThrowOnError extends boolean = false>(
    options: Options<ShowsIdGetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      ShowsIdGetResponses,
      ShowsIdGetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ShowsIdGetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ShowsIdGetResponseSchema.parseAsync(data),
      url: "/shows/{id}",
      ...options,
    });
  }

  /**
   * Update show
   *
   * Update a show by ID.
   */
  public showsIdUpdate<ThrowOnError extends boolean = false>(
    options: Options<ShowsIdUpdateRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).patch<
      ShowsIdUpdateResponses,
      ShowsIdUpdateErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ShowsIdUpdateRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ShowsIdUpdateResponseSchema.parseAsync(data),
      url: "/shows/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get SSE stream
   *
   * Get a stream of Server-Sent Events.
   */
  public sseSubscribe<ThrowOnError extends boolean = false>(
    options?: Options<SseSubscribeRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).sse.get<
      SseSubscribeResponses,
      SseSubscribeErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SseSubscribeRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SseSubscribeResponseSchema.parseAsync(data),
      url: "/sse",
      ...options,
    });
  }

  /**
   * Test
   *
   * Test.
   */
  public testTest<ThrowOnError extends boolean = false>(
    options?: Options<TestTestRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      TestTestResponses,
      TestTestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await TestTestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await TestTestResponseSchema.parseAsync(data),
      url: "/test",
      ...options,
    });
  }
}
