// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * EventType
 *
 * Event types.
 */
export type SseModelsEventType =
  | "test"
  | "show-created"
  | "show-updated"
  | "show-deleted"
  | "event-created"
  | "event-updated"
  | "event-deleted";

/**
 * _Event_type_OrderByInput
 */
export type ShowsModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type ShowsModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type ShowsModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type ShowsModelsEventRelevanceOrderByInput = {
  _relevance: ShowsModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type ShowsModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type ShowsModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type ShowsModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type ShowsModelsWeekdayRule = {
  day: ShowsModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: ShowsModelsWeek | null;
};

export type ShowsModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type ShowsModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type ShowsModelsUpdateRequestInclude = ShowInclude | null;

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type ShowsModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | ShowsModelsFindManyEventArgsFromShow;
};

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type ShowsModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | ShowsModelsEventIdOrderByInput
    | ShowsModelsEventTypeOrderByInput
    | ShowsModelsEventShowIdOrderByInput
    | ShowsModelsEventRelevanceOrderByInput
    | Array<
        | ShowsModelsEventIdOrderByInput
        | ShowsModelsEventTypeOrderByInput
        | ShowsModelsEventShowIdOrderByInput
        | ShowsModelsEventRelevanceOrderByInput
      >;
  where?: ShowsModelsEventWhereInput;
  cursor?: ShowsModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: ShowsModelsEventIncludeFromEvent;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type ShowsModelsShowArgsFromEvent = {
  include?: ShowsModelsShowIncludeFromShow;
};

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type ShowsModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | ShowsModelsShowArgsFromEvent;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type ShowsModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | ShowsModelsStringFilter;
  /**
   * Title
   */
  title?: string | ShowsModelsStringFilter;
  /**
   * Description
   */
  description?: string | ShowsModelsStringFilter | null;
  events?: ShowsModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<ShowsModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<ShowsModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<ShowsModelsShowWhereInput>;
};

/**
 * ShowRelationFilter
 */
export type ShowsModelsShowRelationFilter = {
  is?: ShowsModelsShowWhereInput;
  isNot?: ShowsModelsShowWhereInput;
};

/**
 * EventType
 */
export type ShowsModelsEventType = "live" | "replay" | "prerecorded";

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type ShowsModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | ShowsModelsStringFilter;
  type?: ShowsModelsEventType;
  /**
   * Showid
   */
  showId?: string | ShowsModelsStringFilter;
  show?: ShowsModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<ShowsModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<ShowsModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<ShowsModelsEventWhereInput>;
};

/**
 * StringFilter
 */
export type ShowsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | ShowsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * EventListRelationFilter
 */
export type ShowsModelsEventListRelationFilter = {
  some?: ShowsModelsEventWhereInput;
  none?: ShowsModelsEventWhereInput;
  every?: ShowsModelsEventWhereInput;
};

/**
 * ShowInclude
 *
 * Show relational arguments
 */
export type ShowInclude = {
  /**
   * Events
   */
  events?: boolean | ShowsModelsFindManyEventArgsFromShow;
};

export type ShowsModelsUpdateRequestId = string;

/**
 * ShowUpdateManyMutationInput
 *
 * Arguments for updating many records
 */
export type ShowsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Title
   */
  title?: string;
  /**
   * Description
   */
  description?: string | null;
};

export type ShowsModelsTimezone = string;

/**
 * Show
 *
 * Show data.
 */
export type ShowsModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events that the show belongs to.
   */
  events: Array<ShowsModelsEvent> | null;
};

export type ShowsModelsMonth = number;

export type ShowsModelsMonthday = number | number;

export type ShowsModelsHour = number;

export type ShowsModelsMinute = number;

export type ShowsModelsSecond = number;

/**
 * Frequency
 *
 * Frequency options.
 */
export type ShowsModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export type ShowsModelsRecurrenceRule = {
  frequency: ShowsModelsFrequency;
  /**
   * End datetime of the recurrence in UTC.
   */
  until?: ShowsModelsNaiveDatetime | null;
  /**
   * Count
   *
   * Number of occurrences of the recurrence.
   */
  count?: number | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<ShowsModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<ShowsModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<ShowsModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<ShowsModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<ShowsModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<ShowsModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<ShowsModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<ShowsModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<number> | null;
  /**
   * Start day of the week.
   */
  weekStart?: ShowsModelsWeekday | null;
};

export type ShowsModelsNaiveDatetime = string;

/**
 * Recurrence
 *
 * Recurrence data.
 */
export type ShowsModelsRecurrence = {
  /**
   * Rule of the recurrence.
   */
  rule?: ShowsModelsRecurrenceRule | null;
  /**
   * Include
   *
   * Included datetimes of the recurrence in event timezone.
   */
  include?: Array<ShowsModelsNaiveDatetime> | null;
  /**
   * Exclude
   *
   * Excluded datetimes of the recurrence in event timezone.
   */
  exclude?: Array<ShowsModelsNaiveDatetime> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type ShowsModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: ShowsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show that the event belongs to.
   */
  showId: string;
  /**
   * Show that the event belongs to.
   */
  show: ShowsModelsShow | null;
  start: ShowsModelsNaiveDatetime;
  end: ShowsModelsNaiveDatetime;
  timezone: ShowsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence: ShowsModelsRecurrence | null;
};

/**
 * ShowList
 *
 * List of shows.
 */
export type ShowsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of shows that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned shows.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of shows skipped.
   */
  offset: number | null;
  /**
   * Shows
   *
   * Shows that matched the request.
   */
  shows: Array<ShowsModelsShow>;
};

export type ShowsModelsListRequestWhere = ShowsModelsShowWhereInput | null;

export type ShowsModelsListRequestOrder =
  | ShowOrderByInput
  | Array<ShowOrderByInput>
  | null;

/**
 * _Show_description_OrderByInput
 */
export type ShowDescriptionOrderByInput = {
  /**
   * Description
   */
  description: "asc" | "desc";
};

/**
 * _Show_title_OrderByInput
 */
export type ShowTitleOrderByInput = {
  /**
   * Title
   */
  title: "asc" | "desc";
};

/**
 * _Show_id_OrderByInput
 */
export type ShowIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

export type ShowOrderByInput =
  | ShowIdOrderByInput
  | ShowTitleOrderByInput
  | ShowDescriptionOrderByInput;

export type ShowsModelsListRequestOffset = number | null;

export type ShowsModelsListRequestLimit = number | null;

export type ShowsModelsListRequestInclude = ShowInclude | null;

export type ShowsModelsGetRequestInclude = ShowInclude | null;

export type ShowsModelsGetRequestId = string;

export type ShowsModelsDeleteRequestId = string;

export type ShowsModelsCreateRequestInclude = ShowInclude | null;

/**
 * ShowCreateWithoutRelationsInput
 *
 * Required arguments to the Show create method, without relations
 */
export type ShowsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Title
   */
  title: string;
};

/**
 * _Event_type_OrderByInput
 */
export type ScheduleModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type ScheduleModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type ScheduleModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type ScheduleModelsEventRelevanceOrderByInput = {
  _relevance: ScheduleModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type ScheduleModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type ScheduleModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type ScheduleModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type ScheduleModelsWeekdayRule = {
  day: ScheduleModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: ScheduleModelsWeek | null;
};

export type ScheduleModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type ScheduleModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type ScheduleModelsTimezone = string;

/**
 * StringFilter
 */
export type ScheduleModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | ScheduleModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type ScheduleModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | ScheduleModelsStringFilter;
  /**
   * Title
   */
  title?: string | ScheduleModelsStringFilter;
  /**
   * Description
   */
  description?: string | ScheduleModelsStringFilter | null;
  events?: ScheduleModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<ScheduleModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<ScheduleModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<ScheduleModelsShowWhereInput>;
};

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type ScheduleModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | ScheduleModelsStringFilter;
  type?: ScheduleModelsEventType;
  /**
   * Showid
   */
  showId?: string | ScheduleModelsStringFilter;
  show?: ScheduleModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<ScheduleModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<ScheduleModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<ScheduleModelsEventWhereInput>;
};

/**
 * EventListRelationFilter
 */
export type ScheduleModelsEventListRelationFilter = {
  some?: ScheduleModelsEventWhereInput;
  none?: ScheduleModelsEventWhereInput;
  every?: ScheduleModelsEventWhereInput;
};

/**
 * ShowRelationFilter
 */
export type ScheduleModelsShowRelationFilter = {
  is?: ScheduleModelsShowWhereInput;
  isNot?: ScheduleModelsShowWhereInput;
};

/**
 * EventType
 */
export type ScheduleModelsEventType = "live" | "replay" | "prerecorded";

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type ScheduleModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | ScheduleModelsFindManyEventArgsFromShow;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type ScheduleModelsShowArgsFromEvent = {
  include?: ScheduleModelsShowIncludeFromShow;
};

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type ScheduleModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | ScheduleModelsShowArgsFromEvent;
};

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type ScheduleModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | ScheduleModelsEventIdOrderByInput
    | ScheduleModelsEventTypeOrderByInput
    | ScheduleModelsEventShowIdOrderByInput
    | ScheduleModelsEventRelevanceOrderByInput
    | Array<
        | ScheduleModelsEventIdOrderByInput
        | ScheduleModelsEventTypeOrderByInput
        | ScheduleModelsEventShowIdOrderByInput
        | ScheduleModelsEventRelevanceOrderByInput
      >;
  where?: ScheduleModelsEventWhereInput;
  cursor?: ScheduleModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: ScheduleModelsEventIncludeFromEvent;
};

/**
 * Show
 *
 * Show data.
 */
export type ScheduleModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events that the show belongs to.
   */
  events: Array<ScheduleModelsEvent> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type ScheduleModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: ScheduleModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show that the event belongs to.
   */
  showId: string;
  /**
   * Show that the event belongs to.
   */
  show: ScheduleModelsShow | null;
  start: ScheduleModelsNaiveDatetime;
  end: ScheduleModelsNaiveDatetime;
  timezone: ScheduleModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence: ScheduleModelsRecurrence | null;
};

export type ScheduleModelsMonth = number;

export type ScheduleModelsMonthday = number | number;

export type ScheduleModelsHour = number;

export type ScheduleModelsMinute = number;

export type ScheduleModelsSecond = number;

/**
 * Frequency
 *
 * Frequency options.
 */
export type ScheduleModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export type ScheduleModelsRecurrenceRule = {
  frequency: ScheduleModelsFrequency;
  /**
   * End datetime of the recurrence in UTC.
   */
  until?: ScheduleModelsNaiveDatetime | null;
  /**
   * Count
   *
   * Number of occurrences of the recurrence.
   */
  count?: number | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<ScheduleModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<ScheduleModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<ScheduleModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<ScheduleModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<ScheduleModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<ScheduleModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<ScheduleModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<ScheduleModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<number> | null;
  /**
   * Start day of the week.
   */
  weekStart?: ScheduleModelsWeekday | null;
};

export type ScheduleModelsNaiveDatetime = string;

/**
 * Recurrence
 *
 * Recurrence data.
 */
export type ScheduleModelsRecurrence = {
  /**
   * Rule of the recurrence.
   */
  rule?: ScheduleModelsRecurrenceRule | null;
  /**
   * Include
   *
   * Included datetimes of the recurrence in event timezone.
   */
  include?: Array<ScheduleModelsNaiveDatetime> | null;
  /**
   * Exclude
   *
   * Excluded datetimes of the recurrence in event timezone.
   */
  exclude?: Array<ScheduleModelsNaiveDatetime> | null;
};

/**
 * ScheduleList
 *
 * List of event schedules.
 */
export type ScheduleModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of schedules that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned schedules.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of schedules skipped.
   */
  offset: number | null;
  /**
   * Schedules
   *
   * Schedules that matched the request.
   */
  schedules: Array<Schedule>;
};

/**
 * EventInstance
 *
 * Event instance data.
 */
export type EventInstance = {
  start: ScheduleModelsNaiveDatetime;
  end: ScheduleModelsNaiveDatetime;
};

/**
 * Schedule
 *
 * Schedule data.
 */
export type Schedule = {
  event: ScheduleModelsEvent;
  /**
   * Instances
   *
   * Event instances.
   */
  instances: Array<EventInstance>;
};

export type ScheduleModelsListRequestWhere =
  ScheduleModelsEventWhereInput | null;

export type ScheduleModelsListRequestOrder =
  | ScheduleModelsEventOrderByInput
  | Array<ScheduleModelsEventOrderByInput>
  | null;

export type ScheduleModelsEventOrderByInput =
  | ScheduleModelsEventIdOrderByInput
  | ScheduleModelsEventTypeOrderByInput
  | ScheduleModelsEventShowIdOrderByInput;

export type ScheduleModelsListRequestOffset = number | null;

export type ScheduleModelsListRequestLimit = number | null;

export type ScheduleModelsListRequestInclude =
  ScheduleModelsEventInclude | null;

/**
 * EventInclude
 *
 * Event relational arguments
 */
export type ScheduleModelsEventInclude = {
  /**
   * Show
   */
  show?: boolean | ScheduleModelsShowArgsFromEvent;
};

/**
 * _Event_type_OrderByInput
 */
export type EventsModelsEventTypeOrderByInput = {
  /**
   * Type
   */
  type: "asc" | "desc";
};

/**
 * _Event_showId_OrderByInput
 */
export type EventsModelsEventShowIdOrderByInput = {
  /**
   * Showid
   */
  showId: "asc" | "desc";
};

/**
 * _Event_id_OrderByInput
 */
export type EventsModelsEventIdOrderByInput = {
  /**
   * Id
   */
  id: "asc" | "desc";
};

/**
 * _Event_RelevanceOrderByInput
 */
export type EventsModelsEventRelevanceOrderByInput = {
  _relevance: EventsModelsEventRelevanceInner;
};

/**
 * _Event_RelevanceInner
 */
export type EventsModelsEventRelevanceInner = {
  /**
   * Fields
   */
  fields: Array<"id" | "type" | "showId">;
  /**
   * Search
   */
  search: string;
  /**
   * Sort
   */
  sort: "asc" | "desc";
};

/**
 * _EventWhereUnique_id_Input
 */
export type EventsModelsEventWhereUniqueIdInput = {
  /**
   * Id
   */
  id: string;
};

export type EventsModelsYearday = number | number;

/**
 * WeekdayRule
 *
 * Day rule data.
 */
export type EventsModelsWeekdayRule = {
  day: EventsModelsWeekday;
  /**
   * Occurrence of the day in the year.
   */
  occurrence?: EventsModelsWeek | null;
};

export type EventsModelsWeek = number | number;

/**
 * Weekday
 *
 * Weekday options.
 */
export type EventsModelsWeekday =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type EventsModelsUpdateRequestInclude = EventsModelsEventInclude | null;

/**
 * EventIncludeFromEvent
 *
 * Relational arguments for Event
 */
export type EventsModelsEventIncludeFromEvent = {
  /**
   * Show
   */
  show?: boolean | EventsModelsShowArgsFromEvent;
};

/**
 * ShowArgsFromEvent
 *
 * Arguments for Event
 */
export type EventsModelsShowArgsFromEvent = {
  include?: EventsModelsShowIncludeFromShow;
};

/**
 * EventListRelationFilter
 */
export type EventsModelsEventListRelationFilter = {
  some?: EventsModelsEventWhereInput;
  none?: EventsModelsEventWhereInput;
  every?: EventsModelsEventWhereInput;
};

/**
 * EventWhereInput
 *
 * Event arguments for searching
 */
export type EventsModelsEventWhereInput = {
  /**
   * Id
   */
  id?: string | EventsModelsStringFilter;
  type?: EventsModelsEventType;
  /**
   * Showid
   */
  showId?: string | EventsModelsStringFilter;
  show?: EventsModelsShowRelationFilter;
  /**
   * And
   */
  and?: Array<EventsModelsEventWhereInput>;
  /**
   * Or
   */
  or?: Array<EventsModelsEventWhereInput>;
  /**
   * Not
   */
  not?: Array<EventsModelsEventWhereInput>;
};

/**
 * ShowWhereInput
 *
 * Show arguments for searching
 */
export type EventsModelsShowWhereInput = {
  /**
   * Id
   */
  id?: string | EventsModelsStringFilter;
  /**
   * Title
   */
  title?: string | EventsModelsStringFilter;
  /**
   * Description
   */
  description?: string | EventsModelsStringFilter | null;
  events?: EventsModelsEventListRelationFilter;
  /**
   * And
   */
  and?: Array<EventsModelsShowWhereInput>;
  /**
   * Or
   */
  or?: Array<EventsModelsShowWhereInput>;
  /**
   * Not
   */
  not?: Array<EventsModelsShowWhereInput>;
};

/**
 * StringFilter
 */
export type EventsModelsStringFilter = {
  /**
   * Equals
   */
  equals?: string;
  /**
   * Notin
   */
  notIn?: Array<string>;
  /**
   * Lt
   */
  lt?: string;
  /**
   * Lte
   */
  lte?: string;
  /**
   * Gt
   */
  gt?: string;
  /**
   * Gte
   */
  gte?: string;
  /**
   * Contains
   */
  contains?: string;
  /**
   * Startswith
   */
  startswith?: string;
  /**
   * Endswith
   */
  endswith?: string;
  /**
   * In
   */
  in?: Array<string>;
  /**
   * Not
   */
  not?: string | EventsModelsStringFilter;
  /**
   * Mode
   */
  mode?: "default" | "insensitive";
  /**
   * Search
   */
  search?: string;
};

/**
 * ShowRelationFilter
 */
export type EventsModelsShowRelationFilter = {
  is?: EventsModelsShowWhereInput;
  isNot?: EventsModelsShowWhereInput;
};

/**
 * EventType
 */
export type EventsModelsEventType = "live" | "replay" | "prerecorded";

/**
 * FindManyEventArgsFromShow
 *
 * Arguments for Show
 */
export type EventsModelsFindManyEventArgsFromShow = {
  /**
   * Take
   */
  take?: number;
  /**
   * Skip
   */
  skip?: number;
  /**
   * Orderby
   */
  orderBy?:
    | EventsModelsEventIdOrderByInput
    | EventsModelsEventTypeOrderByInput
    | EventsModelsEventShowIdOrderByInput
    | EventsModelsEventRelevanceOrderByInput
    | Array<
        | EventsModelsEventIdOrderByInput
        | EventsModelsEventTypeOrderByInput
        | EventsModelsEventShowIdOrderByInput
        | EventsModelsEventRelevanceOrderByInput
      >;
  where?: EventsModelsEventWhereInput;
  cursor?: EventsModelsEventWhereUniqueIdInput;
  /**
   * Distinct
   */
  distinct?: Array<"id" | "type" | "showId">;
  include?: EventsModelsEventIncludeFromEvent;
};

/**
 * ShowIncludeFromShow
 *
 * Relational arguments for Show
 */
export type EventsModelsShowIncludeFromShow = {
  /**
   * Events
   */
  events?: boolean | EventsModelsFindManyEventArgsFromShow;
};

/**
 * EventInclude
 *
 * Event relational arguments
 */
export type EventsModelsEventInclude = {
  /**
   * Show
   */
  show?: boolean | EventsModelsShowArgsFromEvent;
};

export type EventsModelsUpdateRequestId = string;

/**
 * EventUpdateInput
 *
 * Input data to update an event.
 */
export type EventsModelsUpdateRequestData = {
  /**
   * Id
   */
  id?: string;
  type?: EventsModelsEventType;
  start?: EventsModelsNaiveDatetime;
  end?: EventsModelsNaiveDatetime;
  timezone?: EventsModelsTimezone;
  /**
   * Recurrence of the event.
   */
  recurrence?: EventsModelsRecurrence | null;
};

export type EventsModelsMonth = number;

export type EventsModelsMonthday = number | number;

export type EventsModelsHour = number;

export type EventsModelsMinute = number;

export type EventsModelsSecond = number;

/**
 * Frequency
 *
 * Frequency options.
 */
export type EventsModelsFrequency =
  | "secondly"
  | "minutely"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly";

/**
 * RecurrenceRule
 *
 * Recurrence rule data.
 */
export type EventsModelsRecurrenceRule = {
  frequency: EventsModelsFrequency;
  /**
   * End datetime of the recurrence in UTC.
   */
  until?: EventsModelsNaiveDatetime | null;
  /**
   * Count
   *
   * Number of occurrences of the recurrence.
   */
  count?: number | null;
  /**
   * Interval
   *
   * Interval of the recurrence.
   */
  interval?: number | null;
  /**
   * Byseconds
   *
   * Seconds of the recurrence.
   */
  bySeconds?: Array<EventsModelsSecond> | null;
  /**
   * Byminutes
   *
   * Minutes of the recurrence.
   */
  byMinutes?: Array<EventsModelsMinute> | null;
  /**
   * Byhours
   *
   * Hours of the recurrence.
   */
  byHours?: Array<EventsModelsHour> | null;
  /**
   * Byweekdays
   *
   * Weekdays of the recurrence.
   */
  byWeekdays?: Array<EventsModelsWeekdayRule> | null;
  /**
   * Bymonthdays
   *
   * Monthdays of the recurrence.
   */
  byMonthdays?: Array<EventsModelsMonthday> | null;
  /**
   * Byyeardays
   *
   * Yeardays of the recurrence.
   */
  byYeardays?: Array<EventsModelsYearday> | null;
  /**
   * Byweeks
   *
   * Weeks of the recurrence.
   */
  byWeeks?: Array<EventsModelsWeek> | null;
  /**
   * Bymonths
   *
   * Months of the recurrence.
   */
  byMonths?: Array<EventsModelsMonth> | null;
  /**
   * Bysetpositions
   *
   * Set positions of the recurrence.
   */
  bySetPositions?: Array<number> | null;
  /**
   * Start day of the week.
   */
  weekStart?: EventsModelsWeekday | null;
};

export type EventsModelsNaiveDatetime = string;

/**
 * Recurrence
 *
 * Recurrence data.
 */
export type EventsModelsRecurrence = {
  /**
   * Rule of the recurrence.
   */
  rule?: EventsModelsRecurrenceRule | null;
  /**
   * Include
   *
   * Included datetimes of the recurrence in event timezone.
   */
  include?: Array<EventsModelsNaiveDatetime> | null;
  /**
   * Exclude
   *
   * Excluded datetimes of the recurrence in event timezone.
   */
  exclude?: Array<EventsModelsNaiveDatetime> | null;
};

export type EventsModelsTimezone = string;

/**
 * Show
 *
 * Show data.
 */
export type EventsModelsShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events that the show belongs to.
   */
  events: Array<EventsModelsEvent> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type EventsModelsEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: EventsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show that the event belongs to.
   */
  showId: string;
  /**
   * Show that the event belongs to.
   */
  show: EventsModelsShow | null;
  start: EventsModelsNaiveDatetime;
  end: EventsModelsNaiveDatetime;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence: EventsModelsRecurrence | null;
};

/**
 * EventList
 *
 * List of events.
 */
export type EventsModelsListResponseResults = {
  /**
   * Count
   *
   * Total number of events that matched the query.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned events.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of events skipped.
   */
  offset: number | null;
  /**
   * Events
   *
   * Events that matched the request.
   */
  events: Array<EventsModelsEvent>;
};

export type EventsModelsListRequestWhere = EventsModelsEventWhereInput | null;

export type EventsModelsListRequestOrder =
  | EventsModelsEventOrderByInput
  | Array<EventsModelsEventOrderByInput>
  | null;

export type EventsModelsEventOrderByInput =
  | EventsModelsEventIdOrderByInput
  | EventsModelsEventTypeOrderByInput
  | EventsModelsEventShowIdOrderByInput;

export type EventsModelsListRequestOffset = number | null;

export type EventsModelsListRequestLimit = number | null;

export type EventsModelsListRequestInclude = EventsModelsEventInclude | null;

export type EventsModelsGetRequestInclude = EventsModelsEventInclude | null;

export type EventsModelsGetRequestId = string;

export type EventsModelsDeleteRequestId = string;

export type EventsModelsCreateRequestInclude = EventsModelsEventInclude | null;

/**
 * EventCreateInput
 *
 * Input data to create an event.
 */
export type EventsModelsCreateRequestData = {
  /**
   * Id
   */
  id?: string;
  /**
   * Showid
   */
  showId?: string;
  type: EventsModelsEventType;
  start: EventsModelsNaiveDatetime;
  end: EventsModelsNaiveDatetime;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence of the event.
   */
  recurrence?: EventsModelsRecurrence | null;
};

/**
 * TimeRangeQuery
 *
 * Query for events in a time range.
 */
export type TimeRangeQuery = {
  /**
   * Type
   *
   * Type of the query.
   */
  type?: "time-range";
  /**
   * Beginning of the time range in UTC.
   */
  start?: EventsModelsNaiveDatetime | null;
  /**
   * End of the time range in UTC.
   */
  end?: EventsModelsNaiveDatetime | null;
};

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<SseModelsEventType> | null;

/**
 * RecurringQuery
 *
 * Query for recurring events.
 */
export type RecurringQuery = {
  /**
   * Type
   *
   * Type of the query.
   */
  type?: "recurring";
  /**
   * Recurring
   *
   * Whether to search for recurring or non-recurring events.
   */
  recurring: boolean;
};

export type Query =
  | ({
      type: "TimeRangeQuery";
    } & TimeRangeQuery)
  | ({
      type: "RecurringQuery";
    } & RecurringQuery);

export type ListRequestStart = ScheduleModelsNaiveDatetime | null;

export type ListRequestQuery = Query | null;

export type ListRequestEnd = ScheduleModelsNaiveDatetime | null;

/**
 * Show
 *
 * Show data.
 */
export type GetResponseShow = {
  /**
   * Id
   *
   * Identifier of the show.
   */
  id: string;
  /**
   * Title
   *
   * Title of the show.
   */
  title: string;
  /**
   * Description
   *
   * Description of the show.
   */
  description: string | null;
  /**
   * Events
   *
   * Events that the show belongs to.
   */
  events: Array<ShowsModelsEvent> | null;
};

/**
 * Event
 *
 * Event data.
 */
export type GetResponseEvent = {
  /**
   * Id
   *
   * Identifier of the event.
   */
  id: string;
  type: EventsModelsEventType;
  /**
   * Showid
   *
   * Identifier of the show that the event belongs to.
   */
  showId: string;
  /**
   * Show that the event belongs to.
   */
  show: EventsModelsShow | null;
  start: EventsModelsNaiveDatetime;
  end: EventsModelsNaiveDatetime;
  timezone: EventsModelsTimezone;
  /**
   * Recurrence rule of the event.
   */
  recurrence: EventsModelsRecurrence | null;
};

export type EventsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of events to return. Default is 10.
     */
    limit?: EventsModelsListRequestLimit | string | null;
    /**
     * Number of events to skip.
     */
    offset?: EventsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find events.
     */
    where?: EventsModelsListRequestWhere | string | null;
    /**
     * Advanced query to apply to find events.
     */
    query?: ListRequestQuery | string | null;
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: EventsModelsListRequestOrder | string | null;
  };
  url: "/events";
};

export type EventsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsListError = EventsListErrors[keyof EventsListErrors];

export type EventsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: EventsModelsListResponseResults;
};

export type EventsListResponse = EventsListResponses[keyof EventsListResponses];

export type EventsCreateRequest = {
  body: EventsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsCreateRequestInclude | string | null;
  };
  url: "/events";
};

export type EventsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsCreateError = EventsCreateErrors[keyof EventsCreateErrors];

export type EventsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: EventsModelsEvent;
};

export type EventsCreateResponse =
  EventsCreateResponses[keyof EventsCreateResponses];

export type EventsIdDeleteRequest = {
  body?: never;
  path: {
    id: EventsModelsDeleteRequestId;
  };
  query?: never;
  url: "/events/{id}";
};

export type EventsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdDeleteError =
  EventsIdDeleteErrors[keyof EventsIdDeleteErrors];

export type EventsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type EventsIdDeleteResponse =
  EventsIdDeleteResponses[keyof EventsIdDeleteResponses];

export type EventsIdGetRequest = {
  body?: never;
  path: {
    id: EventsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsGetRequestInclude | string | null;
  };
  url: "/events/{id}";
};

export type EventsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdGetError = EventsIdGetErrors[keyof EventsIdGetErrors];

export type EventsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseEvent;
};

export type EventsIdGetResponse =
  EventsIdGetResponses[keyof EventsIdGetResponses];

export type EventsIdUpdateRequest = {
  body: EventsModelsUpdateRequestData;
  path: {
    id: EventsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: EventsModelsUpdateRequestInclude | string | null;
  };
  url: "/events/{id}";
};

export type EventsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type EventsIdUpdateError =
  EventsIdUpdateErrors[keyof EventsIdUpdateErrors];

export type EventsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: EventsModelsEvent;
};

export type EventsIdUpdateResponse =
  EventsIdUpdateResponses[keyof EventsIdUpdateResponses];

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type ScheduleListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Start datetime in UTC to filter events instances.
     */
    start?: ListRequestStart | string | null;
    /**
     * End datetime in UTC to filter events instances.
     */
    end?: ListRequestEnd | string | null;
    /**
     * Maximum number of schedules to return. Default is 10.
     */
    limit?: ScheduleModelsListRequestLimit | string | null;
    /**
     * Number of schedules to skip.
     */
    offset?: ScheduleModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find events.
     */
    where?: ScheduleModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: ScheduleModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: ScheduleModelsListRequestOrder | string | null;
  };
  url: "/schedule";
};

export type ScheduleListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ScheduleListError = ScheduleListErrors[keyof ScheduleListErrors];

export type ScheduleListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ScheduleModelsListResponseResults;
};

export type ScheduleListResponse =
  ScheduleListResponses[keyof ScheduleListResponses];

export type ShowsListRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum number of shows to return. Default is 10.
     */
    limit?: ShowsModelsListRequestLimit | string | null;
    /**
     * Number of shows to skip.
     */
    offset?: ShowsModelsListRequestOffset | string | null;
    /**
     * Filter to apply to find shows.
     */
    where?: ShowsModelsListRequestWhere | string | null;
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsListRequestInclude | string | null;
    /**
     * Order to apply to the results.
     */
    order?: ShowsModelsListRequestOrder | string | null;
  };
  url: "/shows";
};

export type ShowsListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsListError = ShowsListErrors[keyof ShowsListErrors];

export type ShowsListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ShowsModelsListResponseResults;
};

export type ShowsListResponse = ShowsListResponses[keyof ShowsListResponses];

export type ShowsCreateRequest = {
  body: ShowsModelsCreateRequestData;
  path?: never;
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsCreateRequestInclude | string | null;
  };
  url: "/shows";
};

export type ShowsCreateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsCreateError = ShowsCreateErrors[keyof ShowsCreateErrors];

export type ShowsCreateResponses = {
  /**
   * Document created, URL follows
   */
  201: ShowsModelsShow;
};

export type ShowsCreateResponse =
  ShowsCreateResponses[keyof ShowsCreateResponses];

export type ShowsIdDeleteRequest = {
  body?: never;
  path: {
    id: ShowsModelsDeleteRequestId;
  };
  query?: never;
  url: "/shows/{id}";
};

export type ShowsIdDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdDeleteError = ShowsIdDeleteErrors[keyof ShowsIdDeleteErrors];

export type ShowsIdDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type ShowsIdDeleteResponse =
  ShowsIdDeleteResponses[keyof ShowsIdDeleteResponses];

export type ShowsIdGetRequest = {
  body?: never;
  path: {
    id: ShowsModelsGetRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsGetRequestInclude | string | null;
  };
  url: "/shows/{id}";
};

export type ShowsIdGetErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdGetError = ShowsIdGetErrors[keyof ShowsIdGetErrors];

export type ShowsIdGetResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: GetResponseShow;
};

export type ShowsIdGetResponse = ShowsIdGetResponses[keyof ShowsIdGetResponses];

export type ShowsIdUpdateRequest = {
  body: ShowsModelsUpdateRequestData;
  path: {
    id: ShowsModelsUpdateRequestId;
  };
  query?: {
    /**
     * Relations to include in the response.
     */
    include?: ShowsModelsUpdateRequestInclude | string | null;
  };
  url: "/shows/{id}";
};

export type ShowsIdUpdateErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type ShowsIdUpdateError = ShowsIdUpdateErrors[keyof ShowsIdUpdateErrors];

export type ShowsIdUpdateResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ShowsModelsShow;
};

export type ShowsIdUpdateResponse =
  ShowsIdUpdateResponses[keyof ShowsIdUpdateResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
